package:
  name: remonet
  version: "0.1.0"

source:
  path: ..

build:
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - remonet

about:
  home: "https://github.com/yourusername/ReMONET"
  license: "MIT"
  summary: "ReMONET: Regridding tools for xarray."
